name: Purge Cloudflare Cache

on:
  deployment_status:
    types: [success]

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        uses: cloudflare/purge-cache-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zoneId: ${{ secrets.CLOUDFLARE_ZONE_ID }}
